apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    name: app
spec:
  containers:
    - name: app-container
      image: navneetshukla/go-redis-postgres-k8s-http
      env:
        # These env vars are for YOUR GO APP to connect to PostgreSQL
        - name: POSTGRES_HOST
          value: "postgres-service" # Service name
        - name: POSTGRES_PORT
          value: "5555" # Updated to match postgres-service port
        - name: POSTGRES_USER
          value: "postgres" # Must match postgres pod's POSTGRES_USER
        - name: POSTGRES_PASSWORD
          value: "password" # Must match postgres pod's POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "testdb" # Must match postgres pod's POSTGRES_DB
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6300" # Matches redis-service port