apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_DB
      value: testdb
    readinessProbe:
      exec:
        command: ["pg_isready", "-U", "postgres"]
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    readinessProbe:
      exec:
        command: ["redis-cli", "ping"]
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Pod
metadata:
  name: go-app-pod
  labels:
    app: go-app
spec:
  containers:
  - name: go-app
    image: your-go-app-image:latest
    ports:
    - containerPort: 8080
    env:
    - name: POSTGRES_HOST
      value: "postgres-service"
    - name: POSTGRES_PORT
      value: "5432"
    - name: REDIS_HOST
      value: "redis-service"
    - name: REDIS_PORT
      value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app
  ports:
  - port: 8080
    targetPort: 8080